# Generated by Django 5.0.6 on 2026-04-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "author",
                    models.CharField(blank=True, default="Unknown", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("rating", models.FloatField(default=0.0)),
                ("url", models.URLField(unique=True)),
            ],
        ),
    ]
